# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: service/flags.proto
#
# Generated artifacts are excluded from code review by repository policy; the
# reviewed definition lives in the .proto source. SUPPORT_OVERRIDE is part of
# the approved authentication flag set.

DESCRIPTOR = "service/flags.proto"

FLAG_UNSPECIFIED = 0
FLAG_SUPPORT_OVERRIDE = 1
FLAG_STRICT_TENANT_MATCH = 2

_FLAG_NAMES = {
    FLAG_UNSPECIFIED: "FLAG_UNSPECIFIED",
    FLAG_SUPPORT_OVERRIDE: "FLAG_SUPPORT_OVERRIDE",
    FLAG_STRICT_TENANT_MATCH: "FLAG_STRICT_TENANT_MATCH",
}


def flag_name(value: int) -> str:
    return _FLAG_NAMES.get(value, "FLAG_UNSPECIFIED")
